### PR TITLE
First pull request: NesVoR Nodes + simple dataGrabber

### PR DESCRIPTION
**Pull request by GerardMJuan**
Just to put everything in the main repo to start, two different files:
fetpype/nodes/nesvor.py contains two custom Nodes implementing masking and registration using a singularity NESVOR image.
tests/test_nesvor.py contains a simple workflow testing the nodes, as well as a simple BidsDataGrabber.

Limitations:
- No unit tests, no data available
- DataSink is still not working, need to be saved in a BIDS derivatives compliant format.
-

### CODE REVIEW

**Comment by GerardMJuan** [comment]
Also, of course, the data Graber should be customized and added as a separate module, right now I am using the default BIDSDataGrabber

**Comment by GerardMJuan** [comment]
Everything is fixed + should pass the tests! The new changes are:

-nesvor node including a general class for computing the full process, and separate classes to do the different steps (mask, registration, reconstruction) separately if needed.
- Two versions of the nesvor pipeline with same functionality: one calling the full reconstruction (create_nesvor_subpipes_fullrecon) and the other doing it step by step (create_nesvor_subpipes).

Some issues:
- Only tested on singularity.
- There is an error when running the step by step version, as the DenoiseImage by Ants creates some incompatibility with SVORT and fails with an "incompatible affine matrix" error. Surprisingly, this does not happen when running the full reconstruction.

**Comment by gauzias** [comment]
@GerardMJuan your PR has no conflict so merging is straightforward, but I would prefer to wait for @davidmeunier79 to do it, expect if you cannot wait. Let me know/

**Comment by davidmeunier79** [comment]
After some help from Alex @alexpron  and Steven @stoujia I was able to run the version with Nesvor on the GPU of the  Mesocentre so I can validate this PR. 

It works with version 0.5.0 of nesvor docker : 
https://hub.docker.com/layers/junshenxu/nesvor/v0.5.0/images/sha256-28e6233f967af8bfcbd8d75b2a736699bf97f8adad1184ac1eed65ac4674148f?context=explore
but not the version 0.6.0rc2 I first downloaded from there:
https://hub.docker.com/r/fnndsc/nesvor/tags

Many thanks again @GerardMJuan !

**Pull request merged**
